### PR TITLE
Cyrillic

### PR DESCRIPTION
**Pull request by StefanPeev**
Cyrillic update.

### CODE REVIEW

**Comment by GuuuWei** [comment]
@StefanPeev  The tnum attribute seems to be invalid in the VF version

**Comment by StefanPeev** [comment]
@GuuuWei What is expected me to do in this situation

**Comment by GuuuWei** [comment]
@StefanPeev  Sorry, I am not an expert in font design. I just found problems when using it as a designer.
I can go on describing the details of the problem, if you are unclear about the tnum attribute.

**Comment by GuuuWei** [comment]
image
tnum and onum are correct when combined, hope this helps

**Comment by driehuis** [comment]
Apologies for being AWOL for so long. Health and family issues have kept me away.

I cannot accept this pull request for a number of reasons. It breaks the build proces. I'm not happy with the number of paths that have been renamed for reasons I do not understand, and adding the entire work directory of FontLab, including path names that will change with future updates and logs, is not desirable.

The tnum issue above illustrates why it is important to be able to track changes in both glyphs and metadata without having to manually find back the working version in an old tree and comparing it to the new one. A lot of time went into cleaning up Dinish to meet Google's ever changing requirements, precisely to prevent issues like this. It is important that the measurable quality of the font stays high. It is essential to have an automated build and test process, and to review every detail, to reach that goal.

I will try to import the cyrillic glyphs into the existing tree, and think about how to properly integrate the variable font into the source tree.

Seeing that this will take some time in the best of times, and these are not the best of times for me, you may want to consider temporarily renaming the variable font to Dinish-VF in Fontlab, and generate variable fonts from them. You can publish them in Releases on your own github page. I am also happy to publish them on the "official" Dinish page as a preview release, if that's okay with you.

I highly appreciate your work, so don't take this as criticism. I'm at fault for being absent (but unfortunately for a reason). You can keep working in the forked tree until we get to a setup where we both can use the same tree without breaking the build.

**Comment by GuuuWei** [comment]
> Apologies for being AWOL for so long. Health and family issues have kept me away.
> 
> I cannot accept this pull request for a number of reasons. It breaks the build proces. I'm not happy with the number of paths that have been renamed for reasons I do not understand, and adding the entire work directory of FontLab, including path names that will change with future updates and logs, is not desirable.
> 
> The tnum issue above illustrates why it is important to be able to track changes in both glyphs and metadata without having to manually find back the working version in an old tree and comparing it to the new one. A lot of time went into cleaning up Dinish to meet Google's ever changing requirements, precisely to prevent issues like this. It is important that the measurable quality of the font stays high. It is essential to have an automated build and test process, and to review every detail, to reach that goal.
> 
> I will try to import the cyrillic glyphs into the existing tree, and think about how to properly integrate the variable font into the source tree.
> 
> Seeing that this will take some time in the best of times, and these are not the best of times for me, you may want to consider temporarily renaming the variable font to Dinish-VF in Fontlab, and generate variable fonts from them. You can publish them in Releases on your own github page. I am also happy to publish them on the "official" Dinish page as a preview release, if that's okay with you.
> 
> I highly appreciate your work, so don't take this as criticism. I'm at fault for being absent (but unfortunately for a reason). You can keep working in the forked tree until we get to a setup where we both can use the same tree without breaking the build.

Thank you for your contribution

**Comment by driehuis** [comment]
I can confirm that the `tnum` issue is caused by the conversions applied by FontLab. FontLab isn't wrong, but it picked the wrong resolution to a conflict in the original sources. Didn't you get a warning about conflicts for, among others, zero.tosf redefining unicode 0030? A more recent version of ufo2ft flagged the issue in the existing tree as well. I've got some changes in the pipeline to improve the `frac` feature; I will have to push those first before I can address the underlying issue.

**Comment by driehuis** [comment]
I've imported your work on Cyrillic glyphs into a separate branch. I really love the way the Cyrillic characters feel like they've always been a part of DINish, excellent work!

I'm in the process of working my way through some production issues. Fontlab papers over contour direction issues, but fontmake turns those into white spots in the glyphs. Those are easy to spot and to fix; I think I got all of them in Dinish-Regular, and I will work my way through the rest of them. I've touched up a few of the glyphs, mostly mechanical changes like making contour direction consistent and addressing concerns from fontbakery. I made a few minor changes for consistency; off the top of my head for Nje and De.

**Pull request closed without merging**
